### PR TITLE
South-Africa-Rustumb-Marz

### PR DESCRIPTION
**Pull request by russmahn**
# Your Details

- Your Name:
- Your City:
- Your Slack Name:

# Homework Details

- Module:
- Week:

### CODE REVIEW

**Review by sinopungula — COMMENTED** [review]
Reviewed your current work, great job!

**Comment by Jontas77** [comment]
Hi Rustumb

Great work buddy, but at the C-comparison exercise you were suppose to use comparison operators and the return result should be a boolean.

**Comment by JarrodBen** [comment]
Great work Rustumb, just make sure that you do the mandatory folder as well, as it is required to be done by the end of today, otherwise keep up the good work.

**Comment by JarrodBen** [comment]
I reviewed your work and you seem to understand what is asked of you for the exercises, Well Done.

**Pull request closed without merging**
